# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012

image: Visual Studio 2015

#  To make the extended ascii characters work on Windows
#  we need to set string encoding for jvm to utf-8 on windows
environment:
  SBT_OPTS: -Dfile.encoding=UTF8
  JAVA_OPTS: -Dfile.encoding=UTF8
  nodejs_version: "4.5.0"
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://piccolo.link/sbt-1.2.1.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - ps: Install-Product node $env:nodejs_version
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd:  call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - cmd:  call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

build_script:
  - sbt clean

test_script:
  - sbt test-plugin