def commonSettings(nameStr: String) = Seq(
  name := nameStr,
  version := Settings.versions.project,
  organization := "com.simianquant",
  description := "A suite of sbt plugins for simplifying creation and distribution of JNI programs",
  scalaVersion := Settings.versions.scala,
  scalacOptions ++= List(
    ("-Xlint:adapted-args,nullary-unit,inaccessible,nullary-override,infer-any,doc-detached,private-shadow," +
      "type-parameter-shadow,poly-implicit-overload,option-implicit,delayedinit-select,by-name-right-associative," +
      "package-object-classes,unsound-match,stars-align,constant"),
    "-Ywarn-unused:imports,patvars,privates,locals",
    "-opt:l:method",
    "-Ywarn-unused-import",
    "-deprecation",
    "-unchecked",
    "-explaintypes",
    "-encoding",
    "UTF-8",
    "-feature",
    "-Xlog-reflective-calls",
    "-Ywarn-inaccessible",
    "-Ywarn-infer-any",
    "-Ywarn-nullary-override",
    "-Ywarn-nullary-unit",
    "-Xfuture"
  ),
  licenses := Seq(("BSD New", url("http://opensource.org/licenses/BSD-3-Clause")))
)

lazy val publishSettings = Seq(
  scmInfo := Some(
      ScmInfo(
        url("https://github.com/SimianQuant/sbt-jni"),
        "scm:git@github.com:SimianQuant/sbt-jni.git"
      )
    ),
    developers := List(
      Developer(
        id = "harshad-deo",
        name = "Harshad Deo",
        email = "harshad@simianquant.com",
        url = url("https://github.com/harshad-deo")
      )
    ),
    homepage := Some(url("https://github.com/SimianQuant/sbt-jni")),
    pomIncludeRepository := { _ =>
      false
    },
    publishTo := {
      val nexus = "https://oss.sonatype.org/"
      if (isSnapshot.value) Some("snapshots" at nexus + "content/repositories/snapshots")
      else Some("releases" at nexus + "service/local/staging/deploy/maven2")
    },
    publishMavenStyle := true
)

lazy val util = project
  .in(file("util"))
  .settings(commonSettings("sbt-jni-util"))
  .settings(publishSettings)
  .disablePlugins(ScriptedPlugin)

lazy val macros = project
  .in(file("macros"))
  .settings(commonSettings("sbt-jni-macros"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scala-lang" % "scala-compiler" % Settings.versions.scala % Provided,
      "org.scala-lang" % "scala-reflect" % Settings.versions.scala,
    ),
    addCompilerPlugin("org.scalamacros" % "paradise" % Settings.versions.macroParadise cross CrossVersion.full)
  )
  .settings(publishSettings)
  .disablePlugins(ScriptedPlugin)
  .dependsOn(util)

lazy val plugin = project
  .in(file("plugin"))
  .settings(commonSettings("sbt-jni"))
  .settings(
    // sbtPlugin := true,
    libraryDependencies += "org.ow2.asm" % "asm" % Settings.versions.asm,
    sourceGenerators in Compile += Def.task {
      val src = s"""|/* Generated by sbt */
                    |package ch.jodersky.sbt.jni
                    |
                    |private[jni] object ProjectVersion {
                    |  final val MacrosParadise = "${Settings.versions.macroParadise}"
                    |  final val Macros = "${Settings.versions.project}"
                    |}
                    |""".stripMargin
      val file = sourceManaged.value / "ch" / "jodersky" / "sbt" / "jni" / "ProjectVersion.scala"
      IO.write(file, src)
      Seq(file)
    }.taskValue,
    scriptedLaunchOpts := Seq(
      "-Dplugin.version=" + Settings.versions.project,
      "-Xmx2g",
      "-Xss2m"
    ),
    scriptedBufferLog := false,
    publishMavenStyle := false,
    bintrayRepository := "sbt-plugins",
    bintrayOrganization in bintray := None
  )
  .enablePlugins(SbtPlugin, ScriptedPlugin)
  .dependsOn(util)

lazy val root = project
  .in(file("."))
  .settings(commonSettings("root"))
  .settings(
    publish := {},
    publishLocal := {},
    // make sbt-pgp happy
    publishTo := Some(Resolver.file("Unused transient repository", target.value / "unusedrepo")),
    addCommandAlias("test-plugin", ";util/publishLocal;macros/publishLocal;scripted")
  )
  .aggregate(macros, plugin)
